Add DataMapping annotation and new configuration
quarkiverse/quarkus-roq pull request #34
Opened 2024-07-02 19:55 UTC by mcruzdev

Fixes #19

2024-07-02 20:52 UTC, melloware requested changes

2024-07-02 20:52 UTC, melloware commented on roq-data/deployment/src/main/java/io/quarkiverse/roq/data/deployment/RoqDataConfig.java
> -        return true;
Don't you also need to check enforceBean in the isEqual?  Typically we compare all the props.

2024-07-03 23:54 UTC, mcruzdev commented
I will squash it after because I mentioned a commit in Zulip.

2024-07-04 13:33 UTC, mcruzdev commented on roq-data/deployment/src/main/java/io/quarkiverse/roq/data/deployment/RoqDataProcessor.java
> +                if (roqDataMapping.isRecord()) {
@ia3andy @mkouba

2024-07-12 09:09 UTC, ia3andy commented
@mcruzdev is it ready for review,

2024-07-12 11:48 UTC, mcruzdev commented
> @mcruzdev is it ready for review?
> 
> 

I stopped because we need definition about how the user will use the data mapping feature.

2024-07-12 11:56 UTC, melloware requested changes

2024-07-12 11:56 UTC, melloware commented on roq-data/deployment/src/main/java/io/quarkiverse/roq/data/deployment/ReadRoqDataProcessor.java
> +                messages.add("The data file '%s' does not match with any data mapping".formatted(name));
```suggestion
                messages.add("The data file '%s' does not match with any @DataMapping class".formatted(name));
```

2024-07-19 23:10 UTC, mcruzdev commented
sorry @ia3andy @melloware  I'm still on vacation. But now we can use parent mapping and `Instance<Type>` mapping.

I think you can take a initial looking.

2024-07-22 11:19 UTC, melloware approved these changes

2024-07-22 12:02 UTC, ia3andy commented
I will give it a try today

2024-07-22 13:26 UTC, ia3andy requested changes
Great stuff!!! Thanks @mcruzdev you roq!

I am getting ClassNotFound exception on a trial local project. I think you need to use Jandex to locate the class:
https://quarkus.io/guides/writing-extensions#scanning-deployments-using-jandex


Could you also add the doc section about data (just add a new page with an index like we do on web-bundler or quinoa, we'll add the rest of the content late)? -- if we don't start it it will be too much to catch up..

2024-07-22 13:38 UTC, ia3andy commented
![image](https://github.com/user-attachments/assets/ca22a1b4-9255-4d0f-aa4a-b006240b67bb)

2024-07-24 18:17 UTC, ia3andy approved these changes

2024-07-24 18:17 UTC, merged

2024-07-24 18:17 UTC, ia3andy commented
@mcruzdev add the doc in another PR ;-)